#ifndef LV_CONF_H
#define LV_CONF_H

#define LV_USE_LOG 0
#define LV_LOG_LEVEL LV_LOG_LEVEL_WARN
#define LV_USE_PERF_MONITOR 0
#define LV_USE_ASSERT_NULL 0
#define LV_USE_ASSERT_MALLOC 0
#define LV_USE_ASSERT_STYLE 0
#define LV_USE_ASSERT_MEM_INTEGRITY 0
#define LV_USE_ASSERT_OBJ 0

#define LV_COLOR_DEPTH 16
#define LV_COLOR_16_SWAP 0

#define LV_USE_BIG_ENDIAN_SYSTEM 0

#define LV_MEM_CUSTOM 0
#define LV_MEM_SIZE (1024U * 64U)
#define LV_MEM_ATTR
#define LV_MEM_ALIGNMENT 4

#define LV_HOR_RES_MAX 240
#define LV_VER_RES_MAX 320

#define LV_DPI_DEF 100

#define LV_USE_TASK_MANAGER 1
#define LV_TASK_HANDLER_IN_DEFAULT_INTR 0

#define LV_USE_GPU_STM32_DMA2D 0
#define LV_USE_GPU_SW_RENDERER 1
#define LV_USE_GPU_LVGL 0
#define LV_USE_GPU_NXP_PXP 0
#define LV_USE_GPU_NXP_VG_LITE 0
#define LV_USE_GPU_VG_LITE 0
#define LV_USE_GPU_STM32_DMABUF 0

#define LV_FONT_MONTSERRAT_8 0
#define LV_FONT_MONTSERRAT_10 0
#define LV_FONT_MONTSERRAT_12 1
#define LV_FONT_MONTSERRAT_14 1
#define LV_FONT_MONTSERRAT_16 1
#define LV_FONT_MONTSERRAT_18 0
#define LV_FONT_MONTSERRAT_20 0
#define LV_FONT_MONTSERRAT_22 0
#define LV_FONT_MONTSERRAT_24 0
#define LV_FONT_MONTSERRAT_26 0
#define LV_FONT_MONTSERRAT_28 0
#define LV_FONT_MONTSERRAT_30 0
#define LV_FONT_MONTSERRAT_32 0
#define LV_FONT_MONTSERRAT_34 0
#define LV_FONT_MONTSERRAT_36 0
#define LV_FONT_MONTSERRAT_38 0
#define LV_FONT_MONTSERRAT_40 0
#define LV_FONT_MONTSERRAT_42 0
#define LV_FONT_MONTSERRAT_44 0
#define LV_FONT_MONTSERRAT_46 0
#define LV_FONT_MONTSERRAT_48 0

#define LV_USE_SYSTEM_FONT 0

#define LV_USE_SDL 0
#define LV_USE_SDL_GPU 0
#define LV_USE_SDL_AUDIO 0

#define LV_USE_FILESYSTEM 0
#define LV_USE_FS_STDIO 0
#define LV_USE_FS_POSIX 0
#define LV_USE_FS_WIN32 0
#define LV_USE_FS_FATFS 0

#define LV_USE_LITTLEFS 0

#define LV_USE_SIMULATOR 0

#define LV_USE_NET 0

#define LV_USE_COLOR_CHROMA_KEY 0

#define LV_USE_ANIMATION 1
#define LV_USE_ANIMATION_COMPLEX 0

#define LV_USE_SHADOW 0
#define LV_USE_LABEL_LONG_MODE 1
#define LV_LABEL_LONG_TXT_HINT 0

#define LV_USE_FLEX 1
#define LV_USE_GRID 1

#define LV_USE_KEYBOARD 0
#define LV_USE_TEXTAREA 0

#define LV_USE_BTN 1
#define LV_USE_BTNMATRIX 0
#define LV_USE_CANVAS 0
#define LV_USE_CHECKBOX 0
#define LV_USE_DROPDOWN 1
#define LV_USE_IMG 1
#define LV_USE_IMGBTN 0
#define LV_USE_LABEL 1
#define LV_USE_LINE 0
#define LV_USE_ROLLER 0
#define LV_USE_SLIDER 0
#define LV_USE_SWITCH 0
#define LV_USE_TABVIEW 0
#define LV_USE_TABLE 0
#define LV_USE_TILEVIEW 0
#define LV_USE_WIN 0

#define LV_USE_METER 0
#define LV_USE_BAR 0
#define LV_USE_GAUGE 0
#define LV_USE_ARC 0

#define LV_USE_CHART 0
#define LV_USE_COLORWHEEL 0
#define LV_USE_SPINBOX 0
#define LV_USE_SPINNER 0

#define LV_USE_MENU 0

#define LV_USE_VIDEO 0

#define LV_USE_USER_DATA 0

#define LV_USE_TRANSFORM 0
#define LV_USE_SCROLLBAR 1
#define LV_USE_SCROLLBAR_FULL_MODE 0
#define LV_USE_GROUP 0
#define LV_USE_GESTURE 0
#define LV_USE_ANIMIMG 0

#define LV_USE_BIDI 0
#define LV_USE_RTL 0
#define LV_USE_ARABIC_PERSIAN_CHARS 0

#define LV_USE_OBJ_REALIGN 0

#define LV_USE_FONT_COMPRESSED 0

#define LV_USE_BMP 0
#define LV_USE_GIF 0
#define LV_USE_JPG 0
#define LV_USE_PNG 0

#define LV_USE_VECTOR_GRAPHICS 0

#define LV_USE_TTF 0

#define LV_USE_FONT_SUBPX 0

#define LV_USE_DISP_MONITOR 0

#define LV_USE_INDEV_MONITOR 0

#define LV_USE_INDEV_ENCODER 0
#define LV_USE_INDEV_BUTTON 0
#define LV_USE_INDEV_KEYBOARD 0

#define LV_USE_COLOR_SCREEN_TRANSP 0

#define LV_USE_PROFILER 0

#define LV_USE_LVGL_ASSERT 0

#define LV_USE_OBJ_GROUP 0

#define LV_USE_EVENT_CB 0

#define LV_USE_USER_DATA 0

#define LV_USE_GC 0

#define LV_USE_LOG 0

#define LV_USE_DEBUG 0

#endif